clc;
clear;
close;
x= input('enter the sequence x =');
y= input('enter the sequence y =');
r=xcorr(x,y);
disp('the cross corelation =');
disp(r);
n=-3:3;
subplot(2,2,1);
plot2d3(x);
title('x sequence');
xlabel('time');
ylabel('amplitude ');
subplot(2,2,2);
plot2d3(y);
title('y sequence');
xlabel('time');
ylabel('amplitude');
subplot(2,2,3);
plot2d3(n,r);
title('cross corelation');
xlabel('time');
ylabel('amplitude');
