clc;
clear; 
close;
N=input('enter the length of sequence ');
n=0:1:N-1;
b=[1];
a=[1,-1,0.9];
x=[1,zeros(1,N-1)];
n=0:1:N-1;
h=filter(b,a,x);
disp(x);
disp(h);
subplot(2,2,1);
plot2d(n,x);
title('impluse function');
xlabel('time');
ylabel('amplitude');
subplot(2,2,2);
plot2d3(n,h);
title('impluse response');
xlabel('time');
ylabel('amplitude');
