x1=input('enter the first sequence');
x2=input('enter the second sequence');
y=conv(x1,x2);
disp('linear con of x1 & x2 is y =');
disp(y);
subplot(2,1,1);
plot2d3(y);
xlabel('time index n');
ylabel('amplitude');
title('convolution o/p');
subplot(2,2,3);
plot2d3(x1);
xlabel('time index n');
ylabel('plot of x1');
subplot(2,2,4);
plot2d3(x2);
xlabel('time index n');
ylabel('amplitude');
title('plot of x2');
