clc;
clear; 
close;
N=input('enter the length of sequence ');
n=0:1:N-1;
b=[1];
a=[1,-1,0.9];
x=cos(0.05*%pi*n);
h=filter(b,a,x);
disp(x);
disp(h);
subplot(2,2,1);
plot2d3(n,x);
title('studystate function');
xlabel('time');
ylabel('amplitude');
subplot(2,2,2);
plot2d3(n,h);
title('studystate response');
xlabel('time');
ylabel('amplitude');
